import {
  DocumentRecord,
  FlashcardSet,
  Flashcard,
  Quiz,
  QuizAttempt,
  RevisionPlan,
  RevisionTask,
  Profile,
  InAppNotification,
} from "@/types/database";

export const MOCK_PROFILE: Profile = {
  id: "user-demo-123",
  full_name: "Alex Morgan",
  avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
  target_exam: "Computer Science & Engineering Board",
  daily_study_goal_mins: 90,
  current_streak: 5,
  longest_streak: 14,
  last_active_date: new Date().toISOString().split("T")[0],
  created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc-1",
    user_id: "user-demo-123",
    title: "Data Structures & Algorithms Mastery Notes.pdf",
    storage_path: "materials/user-demo-123/dsa-notes.pdf",
    file_size: 4820000,
    mime_type: "application/pdf",
    page_count: 42,
    processing_status: "completed",
    extracted_text_snippet:
      "Comprehensive notes on asymptotic notations, binary search trees, graph traversals (BFS/DFS), dynamic programming patterns, and Dijkstra's algorithm with complexity analysis.",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "doc-2",
    user_id: "user-demo-123",
    title: "Thermodynamics & Heat Transfer Fundamentals.pdf",
    storage_path: "materials/user-demo-123/thermo.pdf",
    file_size: 2150000,
    mime_type: "application/pdf",
    page_count: 28,
    processing_status: "completed",
    extracted_text_snippet:
      "Zeroth, First, and Second Laws of thermodynamics. Carnot cycle efficiency limits, entropy generation in closed systems, and heat exchanger design principles.",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "doc-3",
    user_id: "user-demo-123",
    title: "Linear Algebra & Machine Learning Math.pdf",
    storage_path: "materials/user-demo-123/linear-algebra.pdf",
    file_size: 6730000,
    mime_type: "application/pdf",
    page_count: 56,
    processing_status: "completed",
    extracted_text_snippet:
      "Vector spaces, eigenvalues, eigenvectors, Singular Value Decomposition (SVD), principal component analysis (PCA), and matrix calculus for backpropagation.",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_FLASHCARD_SETS: (FlashcardSet & { cards: Flashcard[] })[] = [
  {
    id: "set-1",
    user_id: "user-demo-123",
    document_id: "doc-1",
    title: "DSA High-Yield Exam Flashcards",
    description: "Core algorithms, big-O runtimes, and graph theorems",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    card_count: 6,
    mastered_count: 4,
    cards: [
      {
        id: "c-1",
        set_id: "set-1",
        question: "What is the worst-case time complexity of QuickSort?",
        answer: "O(n²), which occurs when the pivot chosen is consistently the smallest or largest element (e.g. sorted array without random pivot).",
        card_type: "definition",
        mastery_status: "mastered",
        created_at: new Date().toISOString(),
      },
      {
        id: "c-2",
        set_id: "set-1",
        question: "State Dijkstra's algorithm precondition regarding edge weights.",
        answer: "All edge weights must be non-negative (≥ 0). For negative weights, the Bellman-Ford algorithm must be used instead.",
        card_type: "qa",
        mastery_status: "mastered",
        created_at: new Date().toISOString(),
      },
      {
        id: "c-3",
        set_id: "set-1",
        question: "What is the height of a balanced binary search tree with n nodes?",
        answer: "O(log n). Operations like search, insert, and delete run in O(log n) time.",
        card_type: "formula",
        mastery_status: "review",
        created_at: new Date().toISOString(),
      },
      {
        id: "c-4",
        set_id: "set-1",
        question: "Explain the difference between BFS and DFS traversal.",
        answer: "BFS visits nodes level by level using a Queue (ideal for shortest path). DFS explores deep down branches using a Stack/Recursion (ideal for topological sort).",
        card_type: "qa",
        mastery_status: "mastered",
        created_at: new Date().toISOString(),
      },
      {
        id: "c-5",
        set_id: "set-1",
        question: "What are the two key properties of Dynamic Programming problems?",
        answer: "1. Overlapping Subproblems\n2. Optimal Substructure",
        card_type: "definition",
        mastery_status: "mastered",
        created_at: new Date().toISOString(),
      },
      {
        id: "c-6",
        set_id: "set-1",
        question: "What is the time complexity of building a Binary Heap from an array of n elements?",
        answer: "O(n) using Floyd's build-heap bottom-up algorithm, NOT O(n log n).",
        card_type: "formula",
        mastery_status: "new",
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: "quiz-1",
    user_id: "user-demo-123",
    document_id: "doc-1",
    title: "Algorithms & Complexities Mastery Quiz",
    difficulty: "medium",
    topic: "Sorting, Graphs & Dynamic Programming",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    questions: [
      {
        id: "q-1",
        quiz_id: "quiz-1",
        question: "Which of the following sorting algorithms has a guaranteed O(n log n) worst-case time complexity?",
        options: ["QuickSort", "MergeSort", "BubbleSort", "InsertionSort"],
        correct_answer: 1,
        explanation: "MergeSort consistently divides arrays in half and merges sorted sub-arrays, guaranteeing O(n log n) runtime even in worst-case distributions.",
      },
      {
        id: "q-2",
        quiz_id: "quiz-1",
        question: "In a min-heap with n elements, what is the time complexity to extract the minimum element?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        correct_answer: 1,
        explanation: "Extracting the minimum removes the root (O(1)), but requires sift-down heapify on the new root taking O(log n) steps.",
      },
      {
        id: "q-3",
        quiz_id: "quiz-1",
        question: "Which graph representation is more memory-efficient for a sparse graph with V vertices and E edges where E << V²?",
        options: ["Adjacency Matrix", "Adjacency List", "Edge List", "Incidence Matrix"],
        correct_answer: 1,
        explanation: "An adjacency list consumes O(V + E) memory, which is significantly smaller than the O(V²) footprint of an adjacency matrix for sparse graphs.",
      },
      {
        id: "q-4",
        quiz_id: "quiz-1",
        question: "What is the space complexity of Depth-First Search (DFS) on a tree of height h?",
        options: ["O(h)", "O(V)", "O(V + E)", "O(1)"],
        correct_answer: 0,
        explanation: "The call stack memory during DFS is bounded by the maximum recursion depth, which corresponds directly to the height of the tree O(h).",
      },
    ],
  },
];

export const MOCK_QUIZ_ATTEMPTS: QuizAttempt[] = [
  {
    id: "att-1",
    user_id: "user-demo-123",
    quiz_id: "quiz-1",
    quiz_title: "Algorithms & Complexities Mastery Quiz",
    score: 4,
    total_questions: 4,
    time_spent_seconds: 94,
    answers_chosen: [1, 1, 1, 0],
    completed_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "att-2",
    user_id: "user-demo-123",
    quiz_id: "quiz-1",
    quiz_title: "Linear Algebra & Eigenvalues Quick Check",
    score: 3,
    total_questions: 4,
    time_spent_seconds: 120,
    answers_chosen: [0, 2, 1, 1],
    completed_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

export const MOCK_REVISION_PLAN: RevisionPlan & { tasks: RevisionTask[] } = {
  id: "plan-1",
  user_id: "user-demo-123",
  title: "Fall Semester Final Exam Sprint",
  exam_date: new Date(Date.now() + 18 * 86400000).toISOString().split("T")[0],
  available_hours_per_day: 2.5,
  created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  tasks: [
    {
      id: "task-1",
      plan_id: "plan-1",
      user_id: "user-demo-123",
      title: "Review Dijkstra & Bellman-Ford shortest paths",
      topic: "Graph Algorithms",
      scheduled_date: new Date().toISOString().split("T")[0],
      estimated_minutes: 45,
      status: "completed",
      created_at: new Date().toISOString(),
    },
    {
      id: "task-2",
      plan_id: "plan-1",
      user_id: "user-demo-123",
      title: "Practice 15 Flashcards on Dynamic Programming",
      topic: "DP Patterns",
      scheduled_date: new Date().toISOString().split("T")[0],
      estimated_minutes: 30,
      status: "pending",
      created_at: new Date().toISOString(),
    },
    {
      id: "task-3",
      plan_id: "plan-1",
      user_id: "user-demo-123",
      title: "Complete 10-Question Timed Quiz on Sorting & Heaps",
      topic: "Sorting & Trees",
      scheduled_date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
      estimated_minutes: 35,
      status: "pending",
      created_at: new Date().toISOString(),
    },
    {
      id: "task-4",
      plan_id: "plan-1",
      user_id: "user-demo-123",
      title: "Read Chapter 4: Eigenvalues and SVD Matrix Decomposition",
      topic: "Linear Algebra",
      scheduled_date: new Date(Date.now() + 2 * 86400000).toISOString().split("T")[0],
      estimated_minutes: 60,
      status: "pending",
      created_at: new Date().toISOString(),
    },
  ],
};

export const MOCK_NOTIFICATIONS: InAppNotification[] = [
  {
    id: "notif-1",
    user_id: "user-demo-123",
    title: "5-Day Study Streak Reached! 🔥",
    message: "You've practiced every day this week. Keep going to earn the 7-day Master badge!",
    type: "achievement",
    is_read: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "notif-2",
    user_id: "user-demo-123",
    title: "Revision Task Due Today",
    message: "Practice 15 Flashcards on Dynamic Programming to solidify your memory.",
    type: "reminder",
    is_read: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
];
